const WorkHistoryItems = [
  {
    id: 1,
    company_name: "Zingtree",
    company_location: "Larkspur, CA",
    company_url: "https://www.zingtree.com/",
    job_title: "Frontend Engineer",
    job_type: "(Remote Position)",
    job_start_date: "Jan-2022",
    job_stop_date: "Oct-2023",
    accomplishments: [
      "Enhanced and streamlined the new user login experience through the creation of UI components and the integration of Google Sign-In for authentication.",
      "Developed a business intelligence reporting solution using Google Looker and Snowflake.",
      "Conducted thorough code reviews ensuring high-quality code standards and adherence to best practices.",
    ],
    responsibilities:
      "Responsible for frontend and backend development of the Zingtree application solution.",
    skills: ["CSS3", "HTML5", "JavaScript/TypeScript"],
    tools: [
      "AWS",
      "Docker",
      "GithHub",
      "MySQL",
      "PHP",
      "Visual Studio Code",
      "Vue",
    ],
  },
  {
    id: 2,
    company_name: "CHAT Data Services",
    company_location: "Mission Viejo, CA",
    company_url: "https://chatcorenews.com/",
    job_title: "Software Engineer",
    job_type: "(Remote Position)",
    job_start_date: "May-2020",
    job_stop_date: "Oct-2021",
    accomplishments: [
      "Developed the frontend UI components for the data aggregation application using React.",
      "Designed and implemented the server API data models for the data aggregation application.",
      "Enhanced the GitHub source code maintenance operations using GitHub Actions to run tests and control deployment.",
    ],
    responsibilities:
      "Responsible for the design, implementation, and release of the flagship news application.",
    skills: ["CSS3", "HTML5", "JavaScript/TypeScript"],
    tools: [
      "Express",
      "GithHub",
      "Node.js",
      "React",
      "Sequelize ORM",
      "MySQL",
      "Visual Studio Code",
    ],
  },
  {
    id: 3,
    company_name: "WriterAccess",
    company_location: "Boston, MA",
    company_url: "https://www.writeraccess.com/",
    job_title: "Senior Software Engineer",
    job_type: "(Remote Position)",
    job_start_date: "Dec-2018",
    job_stop_date: "Apr-2020",
    accomplishments: [
      "Transitioned the client app to the Vue.js UI framework for data display and state control.",
      "Developed the server API data models using Sequelize and PostgreSQL.",
      "Interacted with GitHub for source code maintenance operations.",
    ],
    responsibilities:
      "Responsibile for development of the User portion of the Writer Access application solution.",
    skills: ["CSS3", "HTML5", "JavaScript/TypeScript"],
    tools: [
      "Express",
      "GithHub",
      "Node.js",
      "Sequelize ORM",
      "PostgreSQL",
      "Visual Studio Code",
      "Vue.js",
    ],
  },
  {
    id: 4,
    company_name: "Advantech B+B Smartworx",
    company_location: "Lake Forest, CA",
    company_url: "https://advantech-bb.com/",
    job_title: "Senior Software Engineer",
    job_type: "",
    job_start_date: "2009",
    job_stop_date: "2018",
    accomplishments: [
      "Managed the software development team to improve efficiency and on-time project completion.",
      "Designed and implemented the iView Network Device Management application.",
      "Designed, built, and implemented the server API data models using MySQL and Java.",
    ],
    responsibilities:
      "Responsible for the design, development, and maintenance of the iView Element Management System (EMS).",
    skills: ["CSS3", "HTML5", "JavaScript"],
    tools: [
      "Apache",
      "Bootstrap",
      "GIT",
      "Java SE 8",
      "Jenkins",
      "jQuery",
      "JSON",
      "MySQL 5",
      "SNMP",
      "TCP/IP",
      "Tomcat",
    ],
  },
  {
    id: 5,
    company_name: "Fair Isaac Corporation",
    company_location: "San Diego, CA (REMOTE)",
    company_url: "https://www.fico.com/",
    job_title: "Lead Software Engineer",
    job_type: "",
    job_start_date: "1999",
    job_stop_date: "2009",
    accomplishments: [
      "Implemented an Internet-based version of the MIRA application",
      "Led the development of the health-care fraud analysis application",
      "Maintained the client data storage requirements",
    ],
    responsibilities:
      "Responsible for the design and implementation of quantitative analysis and predictive software applications involving workers compensation reserving and health-care fraud analysis. ",
    skills: ["C/C++"],
    tools: ["Microsoft SourceSafe", "Visual Studio"],
  },
];
export { WorkHistoryItems };
